"""
This is a program used to calculate the cost for a specific housing plan and 
solar panels that are installed on it.
"""
# Mathematical functions will be needed for this problem, so math is imported.
import math
# The cost of the house is dependent on 7 variables. 
def cost(living_wid, off_len, num_br, br_wid, br_len, mbr_wid, mbr_len):
    """
    This function will calculate the cost of a specific housing plan. It will return the cost of
    the house in dollars.
    """
    # The house floor plan can be divided into three regular rectangles. They can be 
    # divided as follows: 
    # rectangle 1: 2-car garage, kitchen & living
    # rectangle 2: master bed room, master bath
    # rectangle 3: 2 bathrooms, hallway, 'num_br' bedrooms, office
    # The area of each rectangle can be calculated as follows:
    rect_area_1 = 24 * (22 + living_wid) 
    rect_area_2 = mbr_len * (mbr_wid + 12)
    rect_area_3 = (4 + br_wid) * (off_len + 20 + (num_br * br_len))
    
    # The outer perimeter (only includes sides facing outside) of each rectangle can be 
    # calculated as follows:
    rect_per_1 = 68 + (2 * living_wid)
    rect_per_2 = (2 * mbr_len) + (2 * (mbr_wid + 12)) - (4 + br_wid)
    rect_per_3 = (2 * (20 + off_len + (num_br * br_len))) + (4 + br_wid) - 24  
    
    # The cost can be calculated by multiplying the total perimeter by 80 and the total 
    # area by 100 and adding the 2 quantities.
    perimeter_cost = 80 * (rect_per_1 + rect_per_2 + rect_per_3)
    area_cost = 100 * (rect_area_1 + rect_area_2 + rect_area_3)
    total_cost = area_cost + perimeter_cost
    return total_cost

def solar(off_len, num_br, br_wid, br_len, mbr_len):
    """
    This function will calculate the power generated by the solar panels on the house. It will
    return the power in kilowatt hours per day.
    """
    # The solar panels are installed across the roof of the hallway/bedroom wing. 
    # The width of the panel is the side of this wing.
    panel_width = 20 + off_len + (num_br * br_len) + mbr_len
    # The length can be calculated by using trigonometry and the given angle of 25.9 degrees.
    panel_length = (4 + br_wid) / math.cos(math.radians(25.9))
    # The area of the solar panel is given by multiplying its length and width.
    area = panel_width * panel_length
    # This house in question has a few assumptions to be made. It is located in Houston, and the
    # given conditions of its location allow for 
    insolation_meters = 6.1 #kilowatt hours per square meter per day
    # Because the panel and house are measure in feet, this must be converted using 
    # 1 foot = 0.3048 meters. Therefore, 10.7639 foot^2 = 1 meters^2. Insolation in feet is given by
    insolation = ((insolation_meters) / (1 / (0.3048 ** 2)))
    # The solar panels are 22% efficient.
    efficiency = 0.22
    # The total power of the panel is given by the following.
    power_solar = area * insolation * efficiency
    return power_solar
    

